config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, :only => [:index,:show]
    resources :orders,:controller => 'user_orders'
    resources :products
  end
  
  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    post "login" => "auth#login"
    post "logout" => "auth#logout"
    get "products" => "products#index"
    resources :orders, :only => [:create, :show, :index] # ApiV1::OrdersController
    resources :users, :only => :create # ApiV1::UsersController
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations" }

  
  resources :users, :only => :show
  resources :orders, :controller => 'user_orders', :except => :destroy

  
  root to: "welcome#welcome" 

end

app/controllers/admin/user_orders_controller.rb
class Admin::UserOrdersController < AdminController
	before_action :find_user

	def show
		@order = @user.orders.find(params[:id])
	end

	def new
		@order = @user.orders.new
		@order.delivery_address = @user.address
	end
	
	def create
		@order = @user.orders.new(params_order)
		
		if @order.save
			redirect_to admin_user_path(@user)
		else
			render :action => :new 
		end
	end

	def edit
		@order = @user.orders.find(params[:id])
	end

	def update
		@order = @user.orders.find(params[:id])

		if @order.update(params_order)
			redirect_to admin_user_path(@user)
		else
			render :action => :edit
		end
	end

	def destroy
		@order = @user.orders.find(params[:id])
		@order.destroy

		redirect_to admin_user_path(@user)
	end

	protected
	
	def find_user
		@user = User.find(params[:user_id])
	end

	def params_order
		params.require(:order).permit(:family_type_id,:spice, :rice, :delivery_address,:user_id, :delivery_date, :order_items_attributes =>[:status,:product_id, :id])
	end
end

app/controllers/user_orders_controller.rb
class UserOrdersController < ApplicationController
	
	before_action :authenticate_user!

	# => replace @user by current_user

	def index
		@orders = current_user.orders
	end

	def show
		@order = current_user.orders.find(params[:id])

		render :layout => !request.xhr?
	end

	def new
		@order = current_user.orders.new
		@order.delivery_address = current_user.address
	end
	
	def create
		@order = current_user.orders.new(params_order)
		
		if @order.save
		else
			flash[:alert] = @order.errors.full_messages
		end
		redirect_to root_path
	end

	def edit
		@order =current_user.orders.includes(:products).find(params[:id])

	  render :layout => !request.xhr?
	end

	def update
		
		@order =current_user.orders.includes(:products).find(params[:id])

		if @order.update(params_order)
			respond_to do |format|
				format.html
				format.js
			end
			# redirect_to user_path(current_user)
		else

			render :action => :edit
		end
		
	end

	def destroy
		@order =current_user.orders.find(params[:id])
		@order.destroy

		redirect_to user_path(current_user)
	end


	protected

	# Can kill it
	# def find_user
	# 	@user = current_user
	# end

	def params_order
		params.require(:order).permit(:family_type_id,:spice, :rice, :delivery_address, :delivery_date, :order_items_attributes =>[:status,:product_id, :id])
	end
end

app/views/user_orders/_event.html.erb
<div class="modal-header table-container">
	<a class="close-modal" href="#" data-dismiss="modal">
    <span class="menu-icon"></span>
  </a>
	<span>訂單資訊</span>
	<table class="table table-striped">
		<tbody>
			<tr>
				<td><span class="glyphicon glyphicon-user"></span></td>
				<td>訂購人：</td>
				<td><%= @order.user.name %></td>
			</tr>
			<tr>
				<td><i class="fa fa-shopping-basket"></i></td>
				<td>家庭方案：</td>
				<td><%=  @order.family_type.family_type %></td>
			</tr>
			<tr>
				<td><i class="fa fa-money"></i></td>
				<td>價格：</td>
				<td><%=  @order.family_type.price %> NTD</td>
			</tr>
			<tr>
				<td><i class="fa fa-map-marker"></i></td>
				<td>配送地址：</td>
				<td><%= @order.delivery_address %></td>
			</tr>
			<tr>
				<td>	<i class="fa fa-calendar"></i></td>-
				<td>配送日期：</td>
				<td><%=  @order.delivery_date %></td>
			</tr>
		</tbody>
	</table>
</div>
	
<div class="table-container bg-shop">這是您的訂單，
	<b><% if @order.spice == true && @order.rice == true%>
		稻草人會幫您準備辛香料與米
	<% elsif  @order.spice == false && @order.rice == true%>
		稻草人會幫您準備米，如果需要隨箱附加辛香料，請修改您的訂單
	<% elsif @order.spice == true && @order.rice == false %>
		稻草人會幫您準備辛香料，如果需要隨箱附加米，請修改您的訂單
	<% else %>
		如果需要隨箱附加辛香料或米，請修改您的訂單</b>
	<% end %>
</div>	
<div class="table-container">
<%= link_to "回到上一頁",user_path(:id=>@order.user.id), :class=>"remote-load" %>
</div>
	
</div>
<div class= "row table-container">
	<div class="col-xs-6">
		<table class="table table-striped table-hover table-condensed green-text">
			<caption class="green-text">以下是您<b>希望</b>出現在您的菜籃的：</caption>
			<% @order.order_items.each do |o| %>
				<% if o.status == "YES" %>
					<tr>
							<td><ul>
							<li><%=	o.product.name %></li>
							</ul></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	</div>
	<div class="col-xs-6">
		<table class="table table-striped table-hover table-condensed red-text">
			<caption class="red-text">以下是您的<b>不希望</b>出現在您菜籃的：</caption>
			<% @order.order_items.each do |o| %>
				<% if o.status == "No" %>
					<tr>
						<td><ul>
							<li><%=	o.product.name %></li>
						</ul></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	</div>	
</div>	



<script>
	$(".remote-load").click(function(e){
	var this_link = this
  e.preventDefault();

  var url = $(this).attr("href");

  $.ajax(url, {
    success: function(res) {
    	$(this_link).closest(".modal-content").html( res );
    }
  })

})
</script>

app/views/user_orders/_update.js.erb
$('#event_area').html("<%= escape_javascript(render :partial => 'event') %>")
             .css({ backgroundColor: '#ffff99' });

app/views/user_orders/edit.html.erb
<div class="table-container" id="event_area">
	<a class="close-modal" href="#" data-dismiss="modal">
    <span class="menu-icon"></span>
  </a>
	<table class="table table-hover table-condense">
		<%= form_for @order, :url => order_path(@order), :remote => true, :method => :patch do |f| %>
	  <div>
	  	<%= f.label :family_type_id, "家庭方案: "%>
			<%= f.select :family_type_id, FamilyType.all.map {|t| [t.family_type, t.id]}%>
		</div>
	  <div>
	  	<%= f.label :delivery_address, "配送地址: "%>
	  	<%= f.text_field :delivery_address%>
	  </div>
		<div>
			<%= f.label :delivery_date, "配送日期: "%>
			<%= f.date_field :delivery_date ,:type => "text", :data =>{:date_format => 'yyyy-mm-dd'} %>
		</div>
		<div>
			<%= f.label :spice, "選擇是否要辛香料: "%>
			<%= f.check_box :spice %>
		</div>
		<div>
			<%= f.label :rice, "選擇是否要米: "%>
			<%= f.check_box :rice %>
		</div>
	</table>
</div>

	<div class="row">
		<div class="col-xs-3">
			<%= link_to "回到上一頁",user_path(:id=>@order.user.id), :class=>"remote-load"  %>
		</div>
	</div>
	 
	<div class="table-container" id="table-align">
  <%= f.label :order_items, "親自挑選您的菜籃: "%>

		<table class="table table-hover table-condense">
		<%= f.fields_for :order_items do |ff|%>
		
			<tr >
				<td><%= ff.object.product.name %>
				<%= ff.hidden_field	:product_id %>
				<%= ff.hidden_field	:id %></td>	
				<td><%= ff.radio_button :status , "YES" %> Yes </td>
				<td><%= ff.radio_button :status , "Whatever" %> whatever </td>
				<td><%= ff.radio_button :status , "No" %>	No </td>
			</tr>
		<% end %>	
		</table>
	</div>
	<div class="col-xs-3">
		<%= f.submit %>
	</div>
<% end %>	


<script>
	$(".remote-load").click(function(e){
	var this_link = this
  e.preventDefault();

  var url = $(this).attr("href");

  $.ajax(url, {
    success: function(res) {
    	$(this_link).closest(".modal-content").html( res );
    }
  })

})
</script>

app/views/user_orders/new.html.erb
      <div class="modal-header">
        <a class="close-modal" href="#" data-dismiss="modal">
          <span class="menu-icon"></span>
        </a>
      </div>
      <div class="modal-body">
      <%= form_for setup_order(@order), :url => orders_path(@order) do |f| %>
        <div class="row hide" data-step="1" data-title="This is the first step!">
          <img src="img/cup1.jpg" alt="" class="img-responsive">
          <div class="jumbotron">This is step 1
            
            <div>
              <%= f.label :family_type_id, "家庭方案: "%>
              <%= f.select :family_type_id, FamilyType.all.map {|t| [t.family_type, t.id]}%>
            </div>
          </div>
        </div>
        <div class="row hide" data-step="2" data-title="This is the second step!">
          <img src="img/cup2.jpg" alt="" class="img-responsive">
          <div class="jumbotron">This is step 2
            <div>
              <%= f.label :delivery_date, "配送日期: "%>
              <%= f.date_field :delivery_date ,:type => "text", :class =>'datepicker', :data =>{:date_format => 'yyyy-mm-dd'} ,:placeholder => "目前開放週三與週六"    %>
            </div>
          </div>
        </div>
        <div class="row hide" data-step="3" data-title="This is the third step!">
          <img src="img/cup3.jpg" alt="" class="img-responsive">
          <div class="jumbotron">This is step 3
            <div>
              <div>
                <%= f.label :spice, "選擇是否要辛香料: "%>
                <%= f.check_box :spice %>
              </div>
              <div>
                <%= f.label :rice, "選擇是否要米: "%>
                <%= f.check_box :rice %>
              </div> 
              <%= f.label :order_items, "親自挑選您的菜籃: "%>
              <%= f.fields_for :order_items do |ff|%>
                <table class="table">
                  <tr>


                     

                    <td><%= ff.object.product.name %></td>
                    <%= ff.hidden_field :product_id %>
                    <td><%= ff.radio_button :status , "YES" %> Yes</td>
                    <td><%= ff.radio_button :status , "Whatever" %> whatever</td>
                    <td><%= ff.radio_button :status , "No" %> No</td>
                

                  </tr>
                </table>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row hide" data-step="4" data-title="This is the forth step!">
          <img src="img/cup2.jpg" alt="" class="img-responsive">
          <div class="jumbotron">This is step 2
            <div>
              <%= f.label :delivery_address, "配送地址: "%>
              <%= f.text_field :delivery_address, value: current_user.address ,:placeholder => "請輸入您的地址"%>
            </div>

          </div>
        <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning js-btn-step" data-orientation="previous"></button>
        <button type="button" class="btn btn-success js-btn-step" data-orientation="next"></button>
      </div>


<script type="text/javascript">

	$(function () {
		
    $('.datepicker').datepicker({
        daysOfWeekDisabled: [0, 1, 2, 4, 5],
     
    	});
	});
 $('#product-modal').modalSteps({
  btnCancelHtml: 'Cancel',
  btnPreviousHtml: 'Previous',
  btnNextHtml: 'Next',
  btnLastStepHtml: 'Complete',
  disableNextButton: false,
  completeCallback: function(){
    $('#new_order').submit();
  },
  callbacks: {}
  });
</script>

app/views/user_orders/show.html.erb
<div class="modal-header table-container">
	<a class="close-modal" href="#" data-dismiss="modal">
    <span class="menu-icon"></span>
  </a>
	<span>訂單資訊</span>
	<table class="table table-striped">
		<tbody>
			<tr>
				<td><span class="glyphicon glyphicon-user"></span></td>
				<td>訂購人：</td>
				<td><%= @order.user.name %></td>
			</tr>
			<tr>
				<td><i class="fa fa-shopping-basket"></i></td>
				<td>家庭方案：</td>
				<td><%=  @order.family_type.family_type %></td>
			</tr>
			<tr>
				<td><i class="fa fa-money"></i></td>
				<td>價格：</td>
				<td><%=  @order.family_type.price %> NTD</td>
			</tr>
			<tr>
				<td><i class="fa fa-map-marker"></i></td>
				<td>配送地址：</td>
				<td><%= @order.delivery_address %></td>
			</tr>
			<tr>
				<td>	<i class="fa fa-calendar"></i></td>-
				<td>配送日期：</td>
				<td><%=  @order.delivery_date %></td>
			</tr>
		</tbody>
	</table>
</div>
	
<div class="table-container bg-shop">這是您的訂單，
	<b><% if @order.spice == true && @order.rice == true%>
		稻草人會幫您準備辛香料與米
	<% elsif  @order.spice == false && @order.rice == true%>
		稻草人會幫您準備米，如果需要隨箱附加辛香料，請修改您的訂單
	<% elsif @order.spice == true && @order.rice == false %>
		稻草人會幫您準備辛香料，如果需要隨箱附加米，請修改您的訂單
	<% else %>
		如果需要隨箱附加辛香料或米，請修改您的訂單</b>
	<% end %>
</div>	
<div class="table-container">
<%= link_to "回到上一頁",user_path(:id=>@order.user.id), :class=>"remote-load" %>
</div>
	
</div>
<div class= "row table-container">
	<div class="col-xs-6">
		<table class="table table-striped table-hover table-condensed green-text">
			<caption class="green-text">以下是您<b>希望</b>出現在您的菜籃的：</caption>
			<% @order.order_items.each do |o| %>
				<% if o.status == "YES" %>
					<tr>
							<td><ul>
							<li><%=	o.product.name %></li>
							</ul></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	</div>
	<div class="col-xs-6">
		<table class="table table-striped table-hover table-condensed red-text">
			<caption class="red-text">以下是您的<b>不希望</b>出現在您菜籃的：</caption>
			<% @order.order_items.each do |o| %>
				<% if o.status == "No" %>
					<tr>
						<td><ul>
							<li><%=	o.product.name %></li>
						</ul></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	</div>	
</div>	



<script>
	$(".remote-load").click(function(e){
	var this_link = this
  e.preventDefault();

  var url = $(this).attr("href");

  $.ajax(url, {
    success: function(res) {
    	$(this_link).closest(".modal-content").html( res );
    }
  })

})
</script>

app/views/user_orders/update.html.erb
<div class="modal-header table-container">
	<a class="close-modal" href="#" data-dismiss="modal">
    <span class="menu-icon"></span>
  </a>
	<span>訂單資訊</span>
	<table class="table table-striped">
		<tbody>
			<tr>
				<td><span class="glyphicon glyphicon-user"></span></td>
				<td>訂購人：</td>
				<td><%= @order.user.name %></td>
			</tr>
			<tr>
				<td><i class="fa fa-shopping-basket"></i></td>
				<td>家庭方案：</td>
				<td><%=  @order.family_type.family_type %></td>
			</tr>
			<tr>
				<td><i class="fa fa-money"></i></td>
				<td>價格：</td>
				<td><%=  @order.family_type.price %> NTD</td>
			</tr>
			<tr>
				<td><i class="fa fa-map-marker"></i></td>
				<td>配送地址：</td>
				<td><%= @order.delivery_address %></td>
			</tr>
			<tr>
				<td>	<i class="fa fa-calendar"></i></td>-
				<td>配送日期：</td>
				<td><%=  @order.delivery_date %></td>
			</tr>
		</tbody>
	</table>
</div>
	
<div class="table-container bg-shop">這是您的訂單，
	<b><% if @order.spice == true && @order.rice == true%>
		稻草人會幫您準備辛香料與米
	<% elsif  @order.spice == false && @order.rice == true%>
		稻草人會幫您準備米，如果需要隨箱附加辛香料，請修改您的訂單
	<% elsif @order.spice == true && @order.rice == false %>
		稻草人會幫您準備辛香料，如果需要隨箱附加米，請修改您的訂單
	<% else %>
		如果需要隨箱附加辛香料或米，請修改您的訂單</b>
	<% end %>
</div>	
<div class="table-container">
<%= link_to "回到上一頁",user_path(:id=>@order.user.id), :class=>"remote-load" %>
</div>
	
</div>
<div class= "row table-container">
	<div class="col-xs-6">
		<table class="table table-striped table-hover table-condensed green-text">
			<caption class="green-text">以下是您<b>希望</b>出現在您的菜籃的：</caption>
			<% @order.order_items.each do |o| %>
				<% if o.status == "YES" %>
					<tr>
							<td><ul>
							<li><%=	o.product.name %></li>
							</ul></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	</div>
	<div class="col-xs-6">
		<table class="table table-striped table-hover table-condensed red-text">
			<caption class="red-text">以下是您的<b>不希望</b>出現在您菜籃的：</caption>
			<% @order.order_items.each do |o| %>
				<% if o.status == "No" %>
					<tr>
						<td><ul>
							<li><%=	o.product.name %></li>
						</ul></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	</div>	
</div>	



<script>
	$(".remote-load").click(function(e){
	var this_link = this
  e.preventDefault();

  var url = $(this).attr("href");

  $.ajax(url, {
    success: function(res) {
    	$(this_link).closest(".modal-content").html( res );
    }
  })

})
</script>

app/views/user_orders/update.js.erb
$('#event_area').html("<%= escape_javascript(render :partial => 'event') %>")
             .css({ backgroundColor: '#ffff99' });