config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, :only => [:index,:show]
    resources :orders,:controller => 'user_orders'
    resources :products
  end
  
  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    post "login" => "auth#login"
    post "logout" => "auth#logout"
    get "products" => "products#index"
    resources :orders, :only => [:create, :show, :index] # ApiV1::OrdersController
    resources :users, :only => :create # ApiV1::UsersController
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations" }

  
  resources :users, :only => :show
  resources :orders, :controller => 'user_orders', :except => :destroy

  
  root to: "welcome#welcome" 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
	
  has_many :orders, :dependent => :destroy

  before_create :generate_authentication_token

  def admin?
    self.role == "admin" 
  end

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end
  
  def self.get_fb_data(access_token)
    res = RestClient.get "https://graph.facebook.com/v2.4/me",  { :params => { :access_token => access_token } }

    if res.code == 200
      JSON.parse( res.to_str )
    else
      Rails.logger.warn(res.body)
      nil
    end
  end

	def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.name = auth.info.name
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
	
	def index
		@users = User.all
	end

	def show
   	@user = User.find(params[:id])
   	@orders = @user.orders
  end

end

app/controllers/api_v1/users_controller.rb
class ApiV1::UsersController < ApiController
	
 #  def index
	# 	@users = User.all
	# end

	# def show
 #  	@user = User.find(params[:id])
 #  	@orders = @user.orders
 # 	end

 	def create
 		x = User.new(reg_params)
		if x.save
      render :json => { :message => "Registration success!",
                        :auth_token => x.authentication_token,
                        :user_id => x.id}
    else 
    	# validates :email, :uniqueness =>{ :message => "Email has already been registered!" },:status => 401
      render :json => { :message => "Invalid", :errors => @user.errors }, :status => 401
    end
 	end

  protected
	
	def reg_params
		params.permit(:email, :password, :password_confirmation)
	end
	
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
  	@user = User.includes(:orders).find(params[:id])
  	@orders = @user.orders
  	
  	render :layout => false
	end

end

app/helpers/api_v1/users_helper.rb
module ApiV1::UsersHelper
end

app/views/users/show.html.erb
<div class="modal-header">
	<a class="close-modal" href="#" data-dismiss="modal">
    <span class="menu-icon"></span>
  </a>
	<table class="table">
		<tr>
			<td><span class="glyphicon glyphicon-user"></span></td>
			<td><b>姓名:</b></td>
			<td><%= @user.name %></td>	
		</tr>
		<tr>
			<td><i class="fa fa-envelope"></i></td>
			<td><b> E-Mail: </b></td>
			<td><%= @user.email %></td>	
		</tr>
		<tr>
			<td><i class="fa fa-phone "></i></td>
			<td><b>手機號碼: </b></td>
			<td><%= @user.mobile_num %></td>	
		</tr>
		<tr>
			<td><i class="fa fa-map-marker"></i></td>
			<td><b>地址:  </b></td>
			<td><%= @user.address %></td>	
		</tr>
	</table>
</div>

<div class="modal-body row">
	<p class= "col-xs-3"><%= link_to '回到首頁', root_path, :class=> "btn btn-primary"%></p>
 	<p class= "col-xs-3"><%= link_to '新增訂單', root_path( :modal => "product-modal" ), :class=> "btn btn-danger" %>
</div>

<div class="modal-body">
	<table class="table table-striped table-hover .table-condensed">	
		<thead>
			<tr>
				<th>編號#</th>
				<th></th>
				<th>成立日期</th>
				<th>配送日期</th>
			</tr>
		</thead>

		<tbody>
		<% @orders.each do |o| %>
			<tr>
				<td><%= link_to "#{o.number}" , order_path(o), :class => "remote-load" %></td>
				<td><%= link_to '修改', edit_order_path(o), :class => "remote-load" %></td>
				<td><%= o.created_at.to_date.to_formatted_s(:db)%></td>
				<td><%= o.delivery_date.to_formatted_s(:db) %></td>		
			</tr>
		<% end %>
		</tbody>
	</table>
</div>


<script>
	$(".remote-load").click(function(e){
	var this_link = this
  e.preventDefault();

  var url = $(this).attr("href");

  $.ajax(url, {
    success: function(res) {
    	$(this_link).closest(".modal-content").html( res );
    }
  })

})
</script>