config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, :only => [:index,:show]
    resources :orders,:controller => 'user_orders'
    resources :products
  end
  
  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    post "login" => "auth#login"
    post "logout" => "auth#logout"
    get "products" => "products#index"
    resources :orders, :only => [:create, :show, :index] # ApiV1::OrdersController
    resources :users, :only => :create # ApiV1::UsersController
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations" }

  
  resources :users, :only => :show
  resources :orders, :controller => 'user_orders', :except => :destroy

  
  root to: "welcome#welcome" 

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates_presence_of :name ,:category

	has_many :order_items 
	has_many :orders, :through => :order_items

	belongs_to :category
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
	
	def index
		@products = Product.all
	end
	
	def new
		@product = Product.new
	end
	
	def create
		@product = Product.new(product_params)
		
		if @product.save
			redirect_to admin_products_path
		else
			render :action => :new
		end

	end
	
	def show
		@product = Product.find(params[:id])
	end
	
	def edit
		@product = Product.find(params[:id])

	end

	def update
		@product = Product.find(params[:id])
		
		if @product.update(product_params)
			redirect_to admin_products_path
		else
			render :action => :edit 
		end

	end

	def destroy
		@product = Product.find(params[:id])
  	@product.destroy

  	redirect_to admin_products_path
	end

	private
	
	def product_params
		params.require(:product).permit(:name,:category_id, :description)
	end
	



end

app/controllers/api_v1/products_controller.rb
class ApiV1::ProductsController < ApiController
	
	def index
		@products = Product.all
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end
	
	def new
		@product = Product.new
	end
	
	def create
		@product = Product.new(product_params)
		@product.save

		redirect_to products_path
	end
	
	def show
		@product = Product.find(params[:id])
	end
	
	def edit
		@product = Product.find(params[:id])

	end

	def update
		@product = Product.find(params[:id])
		@product.update(product_params)

		redirect_to products_path
	end

	def destroy
		@product = Product.find(params[:id])
  	@product.destroy

  	redirect_to products_path
	end

	private
	
	def product_params
		params.require(:product).permit(:name,:category_id, :description)
	end

end

app/views/admin/products/edit.html.erb
this is product edit page

<%= form_for @product, :url => admin_product_path(@product), :method => :patch do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
		<%= f.collection_select(:category_id, Category.all, :id, :title) %>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Update" %>
<% end %>

<%= link_to "Back to index", admin_products_path%>

app/views/admin/products/index.html.erb
<p>This is product index page</p>
<table>
		
			<tr><% @products.each do |p| %></tr>
		 	  <td><%= p.name %></td>
		  	<td><%= link_to 'Show', admin_product_path(p)%></td>
		  	<td><%= link_to 'Edit', edit_admin_product_path(p)%></td>
		  	<td><%= link_to 'Delete',admin_product_path(p), :method => :delete%></td>
			<% end %>
			
</table>

</br>
<%= link_to 'Add New Product', new_admin_product_path  %>
</br>
<%= link_to '所有使用者', admin_users_path %> 

app/views/admin/products/new.html.erb
this is new product page

<%= form_for @product, :url => admin_products_path do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
		<%= f.collection_select(:category_id, Category.all, :id, :title) %>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Create" %>
<% end %>

<%= link_to "Back to index", admin_products_path%>

app/views/admin/products/show.html.erb
this is product show page

<p><%= @product.name %> </p>
<p><%= @product.category.title %></p>
<p><%= @product.description %> </p>

<%= link_to "Back to index", admin_products_path%>