config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, :only => [:index,:show]
    resources :orders,:controller => 'user_orders'
    resources :products
  end
  
  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    post "login" => "auth#login"
    post "logout" => "auth#logout"
    get "products" => "products#index"
    resources :orders, :only => [:create, :show, :index] # ApiV1::OrdersController
    resources :users, :only => :create # ApiV1::UsersController
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations" }

  
  resources :users, :only => :show
  resources :orders, :controller => 'user_orders', :except => :destroy

  
  root to: "welcome#welcome" 

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>稻草人!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user %>
      <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
      <%= link_to('修改個人資料', edit_registration_path(:user)) %>
       |<%= link_to('查看個人資料', user_path(current_user))%>
    <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %>|
      <%= link_to('登入', new_session_path(:user)) %>|
      <%= link_to "登入 Facebook", user_omniauth_authorize_path(:facebook) %>
      
    <% end %>
		this admin's layout
    <%= yield %>
		
    <%= link_to "後台", admin_products_path%>

  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>稻草人!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <!-- core styles -->
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="img/ico/32.png" sizes="32x32" type="image/png" />
  <link rel="apple-touch-icon-precomposed" href="img/ico/60.png" type="image/png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/ico/72.png" type="image/png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="img/ico/120.png" type="image/png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="img/ico/152.png" type="image/png" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>

<body>

 

  <%= yield %>

  <% if current_user && current_user.admin?%>
  |<%= link_to "後台", admin_products_path%>
  <% end%>

<script>
 $('#product-modal').modalSteps({
  btnCancelHtml: 'Cancel',
  btnPreviousHtml: 'Previous',
  btnNextHtml: 'Next',
  btnLastStepHtml: 'Complete',
  disableNextButton: false,
  completeCallback: function(){
    $('#new_order').submit();
  },
  callbacks: {}
  });

 <% if params[:modal] %>
  $("#<%= params[:modal] %>").modal("show");
  history.replaceState({}, '', '/');
 <% end %>

</script>

</body>
</html>